[build]
  # The build command
  command = "npm run build"

  # The folder to publish (output directory of Vite)
  publish = "dist"

  # Optional: if you want to specify a custom Node.js version
  # If you have a `.nvmrc` or `.node-version` file, Netlify will use that by default.
  # node_version = "16.x"

[build.environment]
  # Set the environment variable for the build
  # If you have environment variables, set them here or in the Netlify UI
  # Example:
  #   - VITE_API_URL = "https://api.example.com"
  
  # You can also use environment variables like:
  #   VITE_PUBLIC_KEY = "your-key"
  #   VITE_SECRET_KEY = "your-secret"

[context.production.environment]
  # Set any production-specific environment variables here
  # Example:
  #   NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-vite"
